name: Run Python Tests
on: [push, pull_request]
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run tests with pytest
        run: pytest 